### ISSUE TITLE
移动端Web开发方案

### ISSUE THREAD

**Issue by VincentLieie** [VincentLieie/blog#2]
# 常用的布局思路
## 媒体查询
```css
body {
    background-color:lightgreen;
}

@media screen and (max-width: 300px) {
    body {
        background-color:lightblue;
    }
}
//如果screen是小于300px会变成淡蓝色;
```
一个常见的例子
```css
body{
    background-color:#0033FF;
}
@media screen and (max-width: 960px){
    body{
    background-color:#FF6699
    }
}

@media screen and (max-width: 768px){
    body{
    background-color:#00FF66;
    }
}

@media screen and (max-width: 550px){
    body{
    background-color:#6633FF;
    }
}

@media screen and (max-width: 320px){
    body{
    background-color:#FFFF00;
    }
}
```
## 栅格化布局
[掘金:栅格化系统](https://juejin.im/post/590bd2d9ac502e00652e20e7)
## 流式布局
也就是俗称的百分比布局,因为宽度是百分比，但是高度是按px来写的
